In [1]:
# Libs and Functions
import numpy as np

In any of states 7 through 9, 12 through 14, or 17 through 19, the Bellman equation is
$$ v(i) = \gamma \left(0.25v(i-5)+0.25v(i+5)+0.25v(i+1)+0.25v(i-1) \right).$$
For states 22 through 24, the Bellman equation is
$$ v(i) = -0.25 + \gamma \left(0.25v(i-5)+0.25v(i)+0.25v(i+1)+0.25v(i-1) \right) .$$
For states 6, 11, and 16, the Bellman equation is
$$ v(i) = -0.25 + \gamma \left(0.25v(i-5)+0.25v(i+5)+0.25v(i+1)+0.25v(i) \right).$$
For states 10, 15, and 20, the Bellman equation is
$$ v(i) = -0.25 + \gamma \left(0.25v(i-5)+0.25v(i+5)+0.25v(i)+0.25v(i-1) \right).$$
For state 3 we write the Bellman equation explicitly:
$$ v(3) = -0.25 + \gamma \left(0.25v(3)+0.25v(8)+0.25v(4)+0.25v(2) \right).$$
The corner states require special care. We have
\begin{align}
v(1)  &= -0.5 + \gamma \left(0.5v(1)+0.25v(2)+0.25v(6)\right)\\
v(5)  &= -0.5 + \gamma \left(0.5v(5)+0.25v(4)+0.25v(10)\right)\\
v(21) &= -0.5 + \gamma \left(0.5v(21)+0.25v(22)+0.25v(17)\right)\\
v(25) &= -0.5 + \gamma \left(0.5v(25)+0.25v(24)+0.25v(20)\right).\\
\end{align}
The constant terms above are the expected rewards. There is a cost for leaving the array and the expected reward is then $P(Leaving)\times -1$. And naturally, states 2 and 4 also require special care
\begin{align}
v(2)  &= 10+\gamma v(22)\\
v(4)  &= 5+\gamma v(19).\\
\end{align}
The system can be expressed in form $Av=b$, with $v$ the vector of value function values, and $b$ a vector with a $-10$ in entry 2, and $-5$ in entry 5. The matrix $A$ can be constructed as given in the statements above. 

In [7]:
A = np.zeros((25,25))
b = np.zeros((25,1))
gamma = 0.9
row = 0
s = [i for i in range(6,9)] + [i for i in range(11,14)] + [i for i in range(16,19)]
for i in s:
    A[row,i] = -1
    A[row,[i-5,i+5,i+1,i-1]] = 0.25 * gamma
    row += 1
for i in range(21,24): # Bottom interior
    A[row,i] = 0.25 * gamma - 1
    A[row,i-5] = 0.25 * gamma
    A[row,i+1] = 0.25 * gamma
    A[row,i-1] = 0.25 * gamma
    b[row] = 0.25
    row += 1
for i in [9, 14, 19]: # Right edge interior
    A[row,i] = 0.25 * gamma - 1
    A[row,i-5] = 0.25 * gamma
    A[row,i+5] = 0.25 * gamma
    A[row,i-1] = 0.25 * gamma
    b[row] = 0.25
    row += 1
for i in [5, 10, 15]: # Left edge interior 
    A[row,i] = 0.25 * gamma - 1
    A[row,i-5] = 0.25 * gamma
    A[row,i+5] = 0.25 * gamma
    A[row,i+1] = 0.25 * gamma
    b[row] = 0.25
    row += 1
# State 3
A[row, 2] = 0.25 * gamma - 1
A[row, 7] = 0.25 * gamma
A[row, 3] = 0.25 * gamma
A[row, 1] = 0.25 * gamma
b[row] = 0.25
row += 1
# Corners
# State 1
A[row, 0] = 0.5 * gamma - 1
A[row, 1] = 0.25 * gamma
A[row, 5] = 0.25 * gamma
b[row] = 0.5
row += 1
# State 5
A[row, 4] = 0.5 * gamma - 1
A[row, 3] = 0.25 * gamma
A[row, 9] = 0.25 * gamma
b[row] = 0.5
row += 1
# State 21
A[row, 20] = 0.5 * gamma - 1
A[row, 21] = 0.25 * gamma
A[row, 16] = 0.25 * gamma
b[row] = 0.5
row += 1
# State 25
A[row, 24] = 0.5 * gamma - 1
A[row, 23] = 0.25 * gamma
A[row, 19] = 0.25 * gamma
b[row] = 0.5
row += 1
# Special States:
# State 2
A[row, 1] = -1
A[row, 21] = 1 * gamma
b[row] = -10
row += 1
# State 4
A[row, 3] = -1
A[row, 18] = 1 * gamma
b[row] = -5
row += 1

v = np.linalg.solve(A,b)
print(np.round(np.reshape(v, (5,5)),2))

[[ 3.35  8.88  4.15  4.43  1.01]
 [ 1.54  2.98  2.1   1.58  0.27]
 [ 0.09  0.74  0.61  0.23 -0.54]
 [-0.87 -0.39 -0.37 -0.64 -1.25]
 [-1.58 -1.25 -1.21 -1.44 -2.01]]
